version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: .
    container_name: celery
    command: celery -A app.celery_app worker --loglevel=info  # Путь к Celery
    depends_on:
      - redis
      - db
    networks:
      - app-network
    user: celeryuser  # Указываем, что контейнер должен работать от этого пользователя

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
